export const AREAS_SHAC: readonly string[] = [
  'Almacén Norte',
  'Almacén Sur',
  'Área de Carga',
  'Área de Contenedores',
  'Archivo Documentario',
  'Auditoría',
  'Calidad',
  'Control de Calidad',
  'Control Documentario',
  'Galpón B',
  'Galpón C',
  'Gerencia',
  'Laboratorio de Calidad',
  'Laboratorio de Muestras',
  'Logística',
  'Operaciones',
  'Operaciones Aduaneras',
  'RR.HH.',
  'SyST',
]
